apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.secret.keyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secret.accessKey | b64enc }}
